### ISSUE TITLE
ImportError: DLL load failed while importing qhull: The specified module could not be found.

### ISSUE THREAD

**Issue by hossam-houssien** [bjpop/hatch#31]
# env
- Python 3.9.2
- OS : Windows 10 1903 build 18362.329
- hatch-0.1.0.0 
- matplotlib-3.4.2 
- numpy-1.20.3 
- pandas-1.2.4 
- scikit-learn-0.24.2 
- seaborn-0.11.2
# issue
- got the following error when run hatch --help 
Traceback (most recent call last):
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\hossam\bin\python\WPy64-3920\python-3.9.2.amd64\Scripts\hatch.exe\__main__.py", line 4, in <module>
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\hatch\hatch.py", line 19, in <module>
    import hatch.plot
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\hatch\plot.py", line 13, in <module>
    import seaborn as sns
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\seaborn\__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\seaborn\rcmod.py", line 7, in <module>
    from . import palettes
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\seaborn\palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\seaborn\utils.py", line 10, in <module>
    from scipy import stats
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\scipy\stats\__init__.py", line 391, in <module>
    from .stats import *
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\scipy\stats\stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "d:\hossam\bin\python\wpy64-3920\python-3.9.2.amd64\lib\site-packages\scipy\spatial\__init__.py", line 98, in <module>
    from .qhull import *
ImportError: DLL load failed while importing qhull: The specified module could not be found.

**Comment by bjpop** [comment]
Thanks @hossam-houssien for the report.

I don't have access to a Windows machine to test this.

However, based on the error it looks like it might be related to a problem with installing scipy on Windows, see for example:

https://stackoverflow.com/questions/34253458/installing-scipy-package-in-windows

There are a few suggested solutions mentioned in stackoverflow that might help. Would you mind checking if any of those help you fix the problem?

Searching for the error also pointed to a number of GitHub issues for Python software on Windows that depends on scipy. Seems like it might be a common problem.

**Comment by hossam-houssien** [comment]
# issue fixed by 
- uninstall scipy and numpy 
- re-install scipy==1.6.1 and numpy==1.20.3

**Comment by bjpop** [comment]
Great, thanks @hossam-houssien. I'm glad you have solved the problem. Thanks for reporting the solution. I will close this now.
